services:
  static-bug-checker:
    container_name: static-bug-checker
    image: static-bug-checker:vul4j
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/StaticBugCheckers
    stdin_open: true
    tty: true